"""seedrace

Revision ID: 047acfbd6858
Revises: 2676251eaa33
Create Date: 2025-06-24 04:49:01.617708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '047acfbd6858'
down_revision: Union[str, None] = '2676251eaa33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'triggers')
    op.add_column('races', sa.Column('triggers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'triggers')
    op.add_column('pets', sa.Column('triggers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
