"""triggers

Revision ID: 2676251eaa33
Revises: 6125e276f092
Create Date: 2025-06-24 04:28:22.644718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2676251eaa33'
down_revision: Union[str, None] = '6125e276f092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('triggers', sa.JSON(), nullable=True))
    op.add_column('user_inventory', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_inventory', 'state')
    op.drop_column('pets', 'triggers')
    op.drop_column('pets', 'species_code')
    # ### end Alembic commands ###
