"""add companion_image to pets

Revision ID: 277d3e0e64cf
Revises: cb7acaab35de
Create Date: 2025-06-15 21:04:51.680820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277d3e0e64cf'
down_revision: Union[str, None] = 'cb7acaab35de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('companion_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'companion_image')
    # ### end Alembic commands ###
