"""fixes

Revision ID: 3500512498e0
Revises: 2402cee774f7
Create Date: 2025-05-31 23:38:31.403719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3500512498e0'
down_revision: Union[str, None] = '2402cee774f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pet_appearance', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('pet_appearance_product_id_fkey'), 'pet_appearance', type_='foreignkey')
    op.create_foreign_key(None, 'pet_appearance', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet_appearance', type_='foreignkey')
    op.create_foreign_key(op.f('pet_appearance_product_id_fkey'), 'pet_appearance', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pet_appearance', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
