"""npc quests

Revision ID: 93ec2eb2cbd0
Revises: d51635f57a5e
Create Date: 2025-06-14 23:07:26.330220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ec2eb2cbd0'
down_revision: Union[str, None] = 'd51635f57a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_npcs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('limit_per_day', sa.Integer(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('rarity_pool', sa.JSON(), nullable=True),
    sa.Column('reward_base', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('npc_id', sa.String(), nullable=True),
    sa.Column('item_requested', sa.JSON(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('failed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['npc_id'], ['quest_npcs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quests_user_id'), 'daily_quests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_quests_user_id'), table_name='daily_quests')
    op.drop_table('daily_quests')
    op.drop_table('quest_npcs')
    # ### end Alembic commands ###
