"""Добавлено display_name в Role

Revision ID: 95a351f8beb0
Revises: c0f2c627be22
Create Date: 2025-06-19 05:53:31.675098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a351f8beb0'
down_revision: Union[str, None] = 'c0f2c627be22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('display_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'display_name')
    # ### end Alembic commands ###
