"""nontrade

Revision ID: b6b12ded6018
Revises: 1950ee25973e
Create Date: 2025-06-25 00:34:26.143835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b12ded6018'
down_revision: Union[str, None] = '1950ee25973e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.add_column('products', sa.Column('non_tradeable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'non_tradeable')
    op.alter_column('pets', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    # ### end Alembic commands ###
