"""new features

Revision ID: cb7acaab35de
Revises: 93ec2eb2cbd0
Create Date: 2025-06-15 15:59:18.919364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7acaab35de'
down_revision: Union[str, None] = '93ec2eb2cbd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('favorite_items', sa.JSON(), nullable=True))
    op.add_column('pets', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('pets', sa.Column('companion_id', sa.Integer(), nullable=True))
    op.add_column('pets', sa.Column('companion_name', sa.String(length=100), nullable=True))
    op.add_column('pets', sa.Column('companion_description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'pets', 'products', ['companion_id'], ['id'])
    op.add_column('products', sa.Column('types', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'types')
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_column('pets', 'companion_description')
    op.drop_column('pets', 'companion_name')
    op.drop_column('pets', 'companion_id')
    op.drop_column('pets', 'biography')
    op.drop_column('pets', 'favorite_items')
    # ### end Alembic commands ###
