"""upd LIKES

Revision ID: d51635f57a5e
Revises: 1b5584d983f8
Create Date: 2025-06-05 09:16:06.021083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51635f57a5e'
down_revision: Union[str, None] = '1b5584d983f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_wall_like_post_user', 'wall_likes', ['post_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wall_like_post_user', 'wall_likes', type_='unique')
    # ### end Alembic commands ###
