"""Add luck and theme_id to User

Revision ID: da33c63d02f3
Revises: 95a351f8beb0
Create Date: 2025-06-21 00:59:59.781246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da33c63d02f3'
down_revision: Union[str, None] = '95a351f8beb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('preview_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('user', sa.Column('luck', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'themes', ['theme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'theme_id')
    op.drop_column('user', 'luck')
    op.drop_table('themes')
    # ### end Alembic commands ###
