version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@omez.net
      PGADMIN_DEFAULT_PASSWORD: 898939
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
